version: "3"
services:
  employees-db:
    build: ./
    image: image_employees_db
    container_name: container_employees_db
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 5432:5432